### ISSUE TITLE
error while building quizzApp

### ISSUE THREAD

**Issue by ghost** [ThibaultGloaguen/quizApp#1]
Hi,

Hope you are all well !

I have the following error when I execute ```tns run android --bundle```

```bash
ERROR in ./app.scss
Module not found: Error: Can't resolve './css/animate.css' in '/Users/x0rzkov/go/src/github.com/x0rzkov/quizApp/app'
 @ ./app.scss 3:10-86
 @ . sync (?<!\bApp_Resources\b.*)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$
 @ ./app.js
```

Is it possible to put it back in the repository please ?

Thanks in advance !

Cheers,
X.

**Comment by ghost** [comment]
Ps. je parle francais aussi !

**Comment by kidz55** [comment]
Yep, I'll do it. I'll keep you in touch

**Comment by ghost** [comment]
thanks for adding the missing file
